version: "3"

services:
  app:
    build: ./.laravel
    container_name: app
    volumes: 
      - ./.laravel:/var/www
    networks: 
      - app-network
    depends_on: 
      - redis
      - db
  
  nginx:
    build: ./.nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports: 
      - "8000:80"
    volumes: 
      - ./.laravel:/var/www
    networks: 
      - app-network
    depends_on: 
      - app
  
  redis:
    image: redis:alpine
    container_name: redis
    expose: 
      - 6379
    networks: 
      - app-network
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.dbdata:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - app-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

networks: 
  app-network:
    driver: bridge
    