version: "3"

services:
  app:
    build: ./.laravel
    container_name: app
    entrypoint: dockerize -template ./.env.tmpl:./.env -wait tcp://db:3306 --timeout 40s ./entrypoint.sh
    volumes: 
      - ./.laravel:/var/www
    environment: 
        - DB_HOST=db
        - DB_PORT=3306
        - DB_DATABASE=laravel
        - DB_USERNAME=root
        - DB_PASSWORD=root
        - REDIS_HOST=redis
    networks: 
      - app-network
    depends_on: 
      - redis
      - db
  
  nginx:
    build: ./.nginx
    container_name: nginx
    entrypoint: dockerize -template /etc/nginx/conf.d/nginx.tmpl:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off;"
    restart: unless-stopped
    tty: true
    ports: 
      - "8000:80"
    volumes: 
      - ./.laravel:/var/www
      - ./.nginx/nginx.tmpl:/etc/nginx/conf.d/nginx.tmpl
    environment: 
      - APP_HOST=app
      - APP_PORT=9000
    networks: 
      - app-network
    depends_on: 
      - app
  
  redis:
    image: redis:alpine
    container_name: redis
    expose: 
      - 6379
    networks: 
      - app-network
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.dbdata:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - app-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

networks: 
  app-network:
    driver: bridge
    